name : generation-doc

on: push

jobs:    
  job2:
     runs-on: ubuntu-lastest
     steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
      - name: generer javadoc
        run: mvn javadoc::javadoc	
      - uses: peaceiris/actions-gh-pages@v3 
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './target/site/apidocs/'	

permissions :
    contents: write
